yatube/about/urls.py
from django.urls import path

from . import views

app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path(
        '',
        views.index,
        name='index',
    ),
    path(
        'group/<slug:slug>/',
        views.group_posts,
        name='group_list',
    ),
    path(
        'create/',
        views.post_create,
        name='post_create',
    ),
    path(
        'posts/<int:post_id>/edit/',
        views.post_edit,
        name='post_edit',
    ),
    path(
        'profile/<str:username>/',
        views.profile,
        name='profile',
    ),
    path(
        'posts/<int:post_id>/',
        views.post_detail,
        name='post_detail',
    ),
    path(
        'posts/<int:post_id>/comment/',
        views.add_comment,
        name='add_comment',
    ),
    path(
        'follow/',
        views.follow_index,
        name='follow_index',
    ),
    path(
        'profile/<str:username>/follow/',
        views.profile_follow,
        name='profile_follow',
    ),
    path(
        'profile/<str:username>/unfollow/',
        views.profile_unfollow,
        name='profile_unfollow',
    ),
]

yatube/yatube/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('posts.urls', namespace='posts')),
    path('about/', include('about.urls', namespace='about')),
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls')),
    path('auth/', include('django.contrib.auth.urls')),
]
if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )
handler404 = 'core.views.page_not_found'
handler403 = 'core.views.permission_denied'
handler500 = 'core.views.server_error'

yatube/posts/models.py
from django.contrib.auth import get_user_model
from django.db import models

User = get_user_model()


class Group(models.Model):
    """
    Модель, описывающая поля БД для "Группы публикаций":
    title       - Название поста,
    slug        - Формат строки, улучшающий читаемость и seo-оптмизацию,
    description - Описание поста.
    Для каждого поля добавлены vebose-name.
    """

    title = models.CharField(
        max_length=200,
        verbose_name='Заголовок',
    )
    slug = models.SlugField(
        unique=True,
        verbose_name='Slug-строка',
    )
    description = models.TextField(
        verbose_name='Описание',
    )

    def __str__(self):
        return self.title


class Post(models.Model):
    """
    Модель, описывающая поля БД для "Публикаций":
    text        - Текст публикации,
    pub_date    - Дата публикации,
    author      - Автор публикации,
    group       - Группа публикации.
    Для каждого поля добавлены vebose-name.
    """

    text = models.TextField(
        verbose_name='Текст публикации',
    )
    pub_date = models.DateTimeField(
        auto_now_add=True,
        verbose_name='Дата',
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts',
        verbose_name='Автор',
    )
    group = models.ForeignKey(
        Group,
        on_delete=models.SET_NULL,
        related_name='posts',
        blank=True,
        null=True,
        verbose_name='Группа',
    )
    image = models.ImageField(
        'Картинка',
        upload_to='posts/',
        blank=True,
    )

    def __str__(self):
        return self.text[:15]

    class Meta:
        ordering = '-pub_date',


class Comment(models.Model):
    """
    Модель, описывающая поля БД для "Комментариев пользователей":
    text        - Текст комментария,
    post        - Ссылка на пост,
    author      - Ссылка на автора поста,
    created     - Дата комментария.
    """
    post = models.ForeignKey(
        Post,
        on_delete=models.CASCADE,
        related_name='comments',
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='comments',
    )
    text = models.TextField()
    created = models.DateTimeField(
        auto_now_add=True,
    )


class Follow(models.Model):
    """
    Модель, описывающая поля БД для "Подписок на авторов":
    user        - Ссылка на пользователя,
    author      - Ссылка на автора, на которого подписан пользователь.
    """
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='follower',
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='following',
    )

yatube/posts/forms.py
from django import forms

from .models import Comment, Post


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = (
            'text',
            'group',
            'image',
        )
        help_texts = {
            'text': 'Текст публикации',
            'group': 'Группа публикации',
            'image': 'Картинка публикации',
        }


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = (
            'text',
        )
        help_texts = {
            'text': 'Текст комментария',
        }

yatube/posts/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404, redirect, render
from django.views.decorators.cache import cache_page

from .forms import CommentForm, PostForm
from .models import Follow, Group, Post, User
from .utils import page_nav


@cache_page(20, key_prefix='index_page')
def index(request):
    """
    Функция обрабатывает запросы к главной странице,
    получает данные из модели Post и связанной модели Group,
    выводит 10 последних постов и рендерит их в шаблон.
    """
    post_list = Post.objects.select_related('group', 'author')
    page_obj = page_nav(request, post_list)
    context = {
        'page_obj': page_obj,
    }

    return render(request, 'posts/index.html', context)


def group_posts(request, slug):
    """
    Функция обрабатывает запросы к странице с публикациями группы,
    получает группу из модели и проверяет url к ней компановщиком slug,
    собирает словарь из данных и рендерит их в шаблон.
    """
    group = get_object_or_404(Group, slug=slug)
    post_list = group.posts.select_related('author')
    page_obj = page_nav(request, post_list)
    context = {
        'group': group,
        'page_obj': page_obj,
    }

    return render(request, 'posts/group_list.html', context)


def profile(request, username):
    """
    Функция обрабатывает запросы к странице профиля пользователя,
    получает посты пользователя, собирает словарь и рендерит шаблон.
    """
    author = get_object_or_404(User, username=username)
    post_list = author.posts.select_related('group')
    following = False
    if request.user.is_authenticated:
        following = Follow.objects.filter(
            user=request.user,
            author=author,
        ).exists()
    page_obj = page_nav(request, post_list)
    context = {
        'author': author,
        'following': following,
        'page_obj': page_obj,
    }

    return render(request, 'posts/profile.html', context)


def post_detail(request, post_id):
    """
    Функция обрабатывает запросы к странице поста.
    """
    post = Post.objects.select_related('group', 'author').get(id=post_id)
    form = CommentForm()
    comments = post.comments.all()
    context = {
        'post': post,
        'form': form,
        'comments': comments,
    }

    return render(request, 'posts/post_detail.html', context)


@login_required
def post_create(request):
    """
    Функция обрабатывает запросы к странице добавления поста.
    После успешной валидации формы добавляется пост, а автор
    перенаправляется на страницу профиля.
    """
    form = PostForm(
        request.POST or None,
        files=request.FILES or None,
    )
    if request.method == 'POST' and form.is_valid():
        post = form.save(commit=False)
        post.author = request.user
        post.save()

        return redirect('posts:profile', post.author)

    return render(
        request,
        'posts/create_post.html',
        {
            'form': form,
        }
    )


@login_required
def post_edit(request, post_id):
    """
    Функция обрабатывает запросы к странице изменения поста.
    Авторы могут редактировать свои посты, чужие только просматривать.
    """
    post = get_object_or_404(Post, pk=post_id)
    is_edit = True
    if post.author != request.user:
        return redirect('posts:post_detail', post_id)

    form = PostForm(request.POST or None, instance=post)
    if request.method == 'POST' and form.is_valid():
        post = form.save(commit=False)
        post.author = request.user
        form.save()

        return redirect('posts:post_detail', post_id)

    return render(
        request,
        'posts/create_post.html',
        {
            'post': post,
            'form': form,
            'is_edit': is_edit,
        }
    )


@login_required
def add_comment(request, post_id):
    """
    Функция обрабатывает запросы к форме добавления комментария.
    После успешной валидации формы добавляется комментарий на
    странице поста.
    """
    post = get_object_or_404(Post, id=post_id)
    form = CommentForm(request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        comment.save()

    return redirect('posts:post_detail', post_id=post_id)


@login_required
def follow_index(request):
    """
    Функция обрабатывает запросы к странице подписок пользователя.
    """
    post_list = Post.objects.filter(author__following__user=request.user)
    page_obj = page_nav(request, post_list)
    context = {
        'page_obj': page_obj,
    }

    return render(request, 'posts/follow.html', context)


@login_required
def profile_follow(request, username):
    """
    Функция подписки на авторов.
    """
    author = get_object_or_404(User, username=username)
    if author != request.user:
        Follow.objects.get_or_create(user=request.user, author=author)

    return redirect('posts:follow_index')


@login_required
def profile_unfollow(request, username):
    """
    Функция отписки от авторов.
    """
    author = get_object_or_404(User, username=username)
    Follow.objects.filter(user=request.user, author=author).delete()

    return redirect('posts:follow_index')

yatube/templates/posts/create_post.html
{% extends 'base.html' %}
{% block title %}
{% if is_edit %}
Редактировать запись
{% else %}
Добавить запись
{% endif %}
{% endblock %}
{% load user_filters %}
{% block content %}
<main>
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-sm-8 p-5">
        <div class="card">
          <div class="card-header">
            {% if is_edit %}
            Редактировать запись
            {% else %}
            Добавить запись
            {% endif %}
          </div>
          <div class="card-body">
            {% include 'includes/form_errors.html' %}
            <form method="post" enctype="multipart/form-data">
              {% csrf_token %}
              {% include 'includes/form.html' %}
              <div class="col-sm-6">
                <button type="submit" class="btn btn-primary">
                  {% if is_edit %}
                  Сохранить
                  {% else %}
                  Добавить
                  {% endif %}
                </button>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
</main>
{% endblock %}

yatube/templates/posts/follow.html
{% extends 'base.html' %}
{% block title %}
Подписки
{% endblock %}
{% block content %}
<div class="container">
  <h1>Мои подписки</h1>
	{% include 'posts/includes/switcher.html' %}
  {% for post in page_obj %}
  {% include 'posts/includes/post.html' %}
  {% if not forloop.last %}<hr>
  {% endif %}
  {% endfor %}
  {% include 'posts/includes/paginator.html' %}
</div>
{% endblock %}

yatube/templates/posts/group_list.html
{% extends 'base.html' %}
{% block title %}Записи сообщества - "{{ group.title }}"{% endblock %}
{% block content %}
<div class="container">
  <h1>{{ group.title }}</h1>
  <p>{{ group.description }}</p>
  {% for post in page_obj %}
  {% include 'posts/includes/post.html' %}
  {% if not forloop.last %}<hr>
  {% endif %}
  {% endfor %}
  {% include 'posts/includes/paginator.html' %}
</div>
{% endblock %}

yatube/templates/posts/index.html
{% extends 'base.html' %}
{% block title %}Последние обновления на сайте{% endblock %}
{% block content %}
<div class="container">
  <h1>Последние обновления на сайте</h1>
  {% include 'posts/includes/switcher.html' %}
  {% for post in page_obj %}
  {% include 'posts/includes/post.html' %}
  {% if not forloop.last %}<hr>{% endif %}
  {% endfor %}
  {% include 'posts/includes/paginator.html' %}
</div>
{% endblock %}

yatube/templates/posts/post_detail.html
{% extends 'base.html' %}
{% block title %}{{ post.text|truncatechars:30 }}{% endblock %}
{% block content %}
{% load thumbnail %}
{% load user_filters %}
<div class="container">
  <div class="row">
    <aside class="col-12 col-md-4">
      <ul class="list-group list-group-flush">
        <li class="list-group-item d-flex justify-content-between align-items-center">
          Дата публикации: <span>{{ post.pub_date|date:"d E Y" }}</span>
        </li>
        <li class="list-group-item d-flex justify-content-between align-items-center">
          Группа: <span>{{ post.group.title }}</span>
        </li>
        <li class="list-group-item d-flex justify-content-between align-items-center">
          Автор: <span>{{ post.author.get_full_name }}</span>
        </li>
        <li class="list-group-item d-flex justify-content-between align-items-center">
          Всего постов автора: <span>{{ post.author.posts.count }}</span>
        </li>
        <li class="list-group-item d-flex justify-content-between align-items-center">
          {% if post.group %}
            <a class="btn btn-primary" href="{% url 'posts:group_list' post.group.slug %}" role="button">Все записи группы</a>
          {% endif %}
          <a class="btn btn-primary" href="{% url 'posts:profile' post.author.username %}" role="button">Все записи пользователя</a>
        </li>
      </ul>
    </aside>
    <article class="col-12 col-md-8">
      {% thumbnail post.image "960x339" crop="28%" upscale=True as im %}
      <img class="card-img my-2" src="{{ im.url }}">
      {% endthumbnail %}
      <p>{{ post.text|linebreaksbr }}</p>
      {% if post.author == request.user %}
      <a class="btn btn-primary" href="{% url 'posts:post_edit' post.id %}" role="button">Редактировать</a>
      {% endif %}
    </article>
    {% include 'posts/includes/comments.html' %}
{% endblock %}

yatube/templates/posts/profile.html
{% extends 'base.html' %}
{% block title %}
Профиль пользователя
{% if author.get_full_name %}
{{ author.get_full_name }}
{% else %}
{{ author.username }}
{% endif %}
{% endblock %}
{% block content %}
<div class="container">
  <h1>
    Все посты пользователя:
    {% if author.get_full_name %}
    {{ author.get_full_name }}
    {% else %}
    {{ author.username }}
    {% endif %}
  </h1>
  <div class="row mb-5">
    <div class="col-8 col-md-4">
      <h3>Всего постов: {{ author.posts.count }}</h3>
    </div>
    <div class="col-8 col-md-4">
      <h3>Всего подписок: {{ author.follower.count }}</h3>
      <h3>Всего подписчиков: {{ author.following.count }}</h3>
    </div>
  </div>
  {% if request.user != user %} 
  {% if following %}
  <a class="btn btn-lg btn-light mb-5 mt-2"
  href="{% url 'posts:profile_unfollow' author.username %}" role="button">Отписаться</a>
  {% else %}
  <a class="btn btn-lg btn-primary mb-5 mt-2"
  href="{% url 'posts:profile_follow' author.username %}" role="button">Подписаться</a>
  {% endif %}
  {% endif %}
  {% for post in page_obj %}
  {% include 'posts/includes/post.html' %}
  {% if not forloop.last %}<hr>
  {% endif %}
  {% endfor %}
  {% include 'posts/includes/paginator.html' %}
</div>
{% endblock %}